### ISSUE TITLE
Clarify how to use "sets" inside of "collection"s in a twig template

### ISSUE THREAD

**Issue by technicallyerik** [bolt/docs#1025]
Given the following content type:

```
sidebar:
    ...
    fields:
        socialnetworks:
            label: "Social Networks"
            type: collection
            fields:
                socialnetwork:
                    type: set
                    label: Social Network
                    fields:
                        name:
                            label: Name
                            type: text
                        icon:
                            label: Icon
                            type: text
                        link:
                            label: Link
                            type: text
            group: content
   ...
```

The only way I could figure out how to display these values in a template were:

```
{% for socialnetwork in sidebar.socialnetworks %}
   {{ socialnetwork.value[0] }} {# name #}
   {{ socialnetwork.value[1] }} {# icon #}
   {{ socialnetwork.value[2] }} {# link #}
{% endfor %}
```

I'm not sure if there is a better way to get each set variable by it's name instead of index.

It might be good to clarify this here: https://docs.bolt.cm/4.0/fields/collection#example-usage-in-templates
