### ISSUE TITLE
Missing docs on "upload" paths

### ISSUE THREAD

**Issue by peterboorsma** [bolt/docs#1033]
The standard upload path for images in records is `/files` so it seems. That is different from Bolt 3 where files are automagically uploaded to YYYY-MM folders.

I can't find documentation about the upload options in Bolt 4. What are the options for "upload"?

```
        image:
            type: image
            group: media
            upload: entries
```

PS
I'd like to be able to upload files to folders like /files/contenttype/YYYY-MM
Is this possible?
