### ISSUE TITLE
Get records with specific selected select-type value

### ISSUE THREAD

**Issue by DebugAndConquer** [bolt/docs#1163]
So I have a content type of regions:

```
regions:
    name: Regions
    singular_name: Region
    fields:
        r_id:
            type: number
            mode: integer
            required: true
        title:
            type: text
            class: large
            required: true
        slug:
            type: slug
            uses: r_id
    record_template: region.twig
    listing_template: regionList.twig
    listing_records: 20
    records_per_page: 20
```
And I have a contenttype of internships that uses the above:
```
internships:
    name: Internships
    singular_name: Internship
    fields:
     ...
        city:
            type: select
            label: City
            values: regions/{title}
            sort: title
            autocomplete: true
            required: true
        ...
    relations:
      ...
   ...
```
In my webapp I need to filter entries by city. How do I write the filtering query to select all internships where selected city is exactly one of the list?
