### ISSUE TITLE
Update with instructions on how to use fields like "description".

### ISSUE THREAD

**Issue by irro** [bolt/docs#276]
The documentation should be updated to explain how to use all of the different fields like "description".  I can't find anything in the documentation that explains it and every way I try to use it as a field in contenttypes.yml creates an error when I try to check my database.

The list is here:
https://docs.bolt.cm/contenttypes-and-records
And on the cheat sheet.

**My contenttype.yml usage is:**
```apps:
    name: Apps
    singular_name: Appitem
    fields:
        description: "Useful applications for people with Mast Cell Disease."
        title: 
        	type: text
        	class: large
```

**The error is generally this:**
In the contenttype for 'Appitem', the field 'description' has 'type: ', which is not a proper field type. Please edit contenttypes.yml, and correct this.

**Comment by GawainLynch** [comment]
With the `description` that itself is a ContentType properly not a field property, and I am not even sure we use it any longer… @bobdenotter?

With the field question you can have multiple fields of the same type, and they do require a unique ID… but what might have gotten lost in translation on IRC was what *is* an ID :grin: 

So in this example, `title`, `slug`, `name`, `breed` and `colour` are all field IDs
```yaml
kittens:
    name: Kittens
    singular_name: Kiten
    description: Something something darkside
    fields:
        title:
            type: text
        slug:
            type: slug
            uses: title
        name:
            type: text
        breed:
            type: text
        colour:
            type: text
```
