### ISSUE TITLE
float min and max values don't work in bolt v3

### ISSUE THREAD

**Issue by jadwigo** [bolt/docs#315]
A content type with the following field does not listen to the min, max and step values

``` yml
    vote:
      type: float
      requred: true
      label: Vote
      min: 0
      max: 10
      step: 0.1
```
