### ISSUE TITLE
Get records with specific taxonomy value

### ISSUE THREAD

**Issue by egoentoro** [bolt/docs#38]
Hi, can someone please tell me how do I get records of all entries with specific taxonomy value. For example all records with category: work.

Thank you in advance!

**Comment by Spomsoree** [comment]
I'm guessing the search term needs to be the taxonomy option **key**. Am I right?
I'm currently not able to get it running.

Here are my taxonomies:
```
categories:
    name:          Kategorien
    slug:          categories
    singular_name: Kategorie
    singular_slug: category
    behaves_like:  categories
    multiple:      true
    options:
        buildingLaw:     Baurecht
        employmentLaw:   Arbeitsrecht
        ...
```

I've got a select field, which prints all the taxonomy options:
![image](https://user-images.githubusercontent.com/14187981/62948034-f361a780-bde3-11e9-9889-7cd51b34baa8.png)

If the user selects one of this options I'd like to start a query which only returns items linked to the selected taxonomy.

Since the taxonomy is named **categories**, I'm now trying to get the entries with the selected categories like this:
![image](https://user-images.githubusercontent.com/14187981/62948227-463b5f00-bde4-11e9-9abb-3f4e1e68f4cf.png)

`currentFilter` is the taxonomy option key, like **employmentLaw** for example.
I've also tried to get the items via the taxonomy option **name**, but that did not work either.

Thank you for any help in advance.

**Comment by Spomsoree** [comment]
I've also tried to adjusted my setup as close to the documentation as possible:

The taxonomy:
```
categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options: [news, events, movies, music, books, life, love, fun]
```

The news contenttype:
```
news:
    name: Newsroom
    singular_name: Newsroom
    slug: aktuelles
    default_status: published
    record_template: news-item.twig
    listing_template: news.json.twig
    listing_records: 10000
    icon_many: 'fa:newspaper-o'
    icon_one: 'fa:newspaper-o'
    taxonomy: categories
    fields:
         ...
```

My debugging code: 
```
{% set currentFilter = app.request.get('c') %}

{# List all categories linked to the a record #}
{{ dump(records|first.taxonomy.categories) }}

{# The applied filter #}
{{ dump(currentFilter) }}

{# The query #}
{% setcontent records = 'news' where { categories: currentFilter } %}

{# The result #}
{{ dump(records|length) }}
```

The output:
![image](https://user-images.githubusercontent.com/14187981/63428832-c2ebc000-c418-11e9-8ead-9f775c50f09b.png)

@bobdenotter do you see anything wrong with this code or is this a bug in the bolt version v3.6.8?

The documentation I'm following:

- https://docs.bolt.cm/3.6/templating/content-fetching#using-taxonomies
- https://docs.bolt.cm/3.6/contenttypes/taxonomies
